# Find the native T6M1BASE headers and libraries.
#
#  T6M1BASE_LIBRARIES    - List of libraries when using nana.
#  T6M1BASE_FOUND        - True if nana found.

# Look for the library.
FIND_LIBRARY(T6M1BASE_LIBRARY NAMES FOSSSimT6M1base HINTS ${CMAKE_SOURCE_DIR}/lib)
MARK_AS_ADVANCED(T6M1BASE_LIBRARY)

# handle the QUIETLY and REQUIRED arguments and set T6M1BASE_FOUND to TRUE if 
# all listed variables are TRUE
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(T6M1BASE DEFAULT_MSG T6M1BASE_LIBRARY)

IF(T6M1BASE_FOUND)
  SET(T6M1BASE_LIBRARIES ${T6M1BASE_LIBRARY})
ELSE(T6M1BASE_FOUND)
  SET(T6M1BASE_LIBRARIES)
ENDIF(T6M1BASE_FOUND)